// client/src/demo/mockData.js
// Authentic mock dataset for Museo Bulawan Management Information System (MB_MIS)

export const demoUser = {
  id: 1,
  fname: "Louis",
  lname: "Ricafrente",
  full_name: "Louis Ricafrente",
  username: "admin",
  email: "admin@museobulawan.ph",
  role: "Admin",
  roleId: 1,
  phone: "0917-888-9999",
  created_at: "2024-01-15T08:00:00.000Z",
};

export const demoUsersList = [
  demoUser,
  {
    id: 2,
    fname: "Elena",
    lname: "Santos",
    full_name: "Elena Santos",
    username: "curator_elena",
    email: "elena.santos@museobulawan.ph",
    role: "ContentManager",
    roleId: 2,
    phone: "0918-777-6666",
    created_at: "2024-02-10T09:30:00.000Z",
  },
  {
    id: 3,
    fname: "Marco",
    lname: "Diaz",
    full_name: "Marco Diaz",
    username: "staff_marco",
    email: "marco.diaz@museobulawan.ph",
    role: "Staff",
    roleId: 5,
    phone: "0919-666-5555",
    created_at: "2024-03-01T10:15:00.000Z",
  },
  {
    id: 4,
    fname: "Carla",
    lname: "Vinzons",
    full_name: "Carla Vinzons",
    username: "reviewer_carla",
    email: "carla.v@museobulawan.ph",
    role: "Reviewer",
    roleId: 4,
    phone: "0920-555-4444",
    created_at: "2024-04-12T11:00:00.000Z",
  }
];

export const demoInvitations = [
  {
    id: 1,
    email: "researcher.danilo@cnsc.edu.ph",
    roleId: 3,
    role: "Viewer",
    status: "Pending",
    created_at: "2024-09-15T08:00:00.000Z",
    expires_at: "2026-12-31T23:59:59.000Z"
  }
];

export const demoRouterFlags = {
  login: true,
  catalogs_public: true,
  home: true,
  appointment_public: true,
  articles_public: true,
  about: true,
  acquisition_public: true,
  inventory: true,
  acquisition: true,
  schedule: true,
  article: true,
  appointment: true,
  files: true,
  logs: true,
  user: true,
  config: true,
  sandbox: true,
  down: false,
  maintenance: false,
  nomatch: true,
};

export const demoAdminFlags = Object.entries(demoRouterFlags).map(([route_key, is_enabled]) => ({
  route_key,
  is_enabled,
  is_public: ["login", "catalogs_public", "home", "appointment_public", "articles_public", "about", "acquisition_public"].includes(route_key),
}));

export const demoArtifacts = [
  {
    contribution_id: 1,
    artifact_id: 1,
    catalog_id: 1,
    title: "Paracale Pre-Colonial Gold Bead Necklace",
    donor_name: "Hon. Manuel Carpio",
    contributor_name: "Hon. Manuel Carpio",
    provenance: "Paracale, Camarines Norte",
    culture: "Pre-Colonial Bicolano (12th-14th Century)",
    acquisition_date: "2023-04-15",
    contribution_type: "donation",
    display_status: "On Display",
    current_location: "Main Gallery - Bulawan Gold Wing",
    on_display: true,
    last_maintenance_at: "2024-06-10",
    contract_expires_at: null,
    donor_description: "Excavated in the ancient alluvial gold mining corridors of Paracale. Features heavy granulated beads of fine gold craftsmanship.",
    curatorial_description: "Exquisite testament to pre-colonial Philippine metallurgy, verifying historical trade networks between Camarines Norte and East Asian maritime merchants.",
    images: ["39418-20250919-853771693.webp"],
    image_urls: ["/uploads/pictures/39418-20250919-853771693.webp"],
    related_image_urls: ["/uploads/pictures/41984-20250919-640949130.webp"],
    dimensions: JSON.stringify([{ label: "Length", value: "42 cm" }, { label: "Weight", value: "78.4 grams" }]),
    material: "22K Native Gold",
    condition_status: "Excellent",
    created_at: "2023-04-15T09:00:00.000Z",
    updated_at: "2024-06-10T14:30:00.000Z",
  },
  {
    contribution_id: 2,
    artifact_id: 2,
    catalog_id: 2,
    title: "Fernando Amorsolo - Afternoon Meal of the Worker",
    donor_name: "Vinzons Heritage Trust",
    contributor_name: "Vinzons Heritage Trust",
    provenance: "Daet, Camarines Norte",
    culture: "Modern Philippine Masterwork (1942)",
    acquisition_date: "2022-11-20",
    contribution_type: "lending",
    display_status: "On Display",
    current_location: "Fine Arts Exhibition Hall",
    on_display: true,
    last_maintenance_at: "2024-05-12",
    contract_expires_at: "2027-11-20",
    donor_description: "Original oil painting depicting farmers in pastoral Camarines Norte sharing a peaceful meal under the mango tree canopy.",
    curatorial_description: "Signature Amorsolo backlighting technique illustrating countryside resilience and daily agrarian life during wartime.",
    images: ["06-AfternoonMealOfTheWorker 1.svg"],
    image_urls: ["/assets/06-AfternoonMealOfTheWorker 1.svg"],
    related_image_urls: ["/assets/Fernando-Amorsolo-Women-Bathing-and-Washing Clothes-7463.svg"],
    dimensions: JSON.stringify([{ label: "Canvas", value: "60 x 80 cm" }]),
    material: "Oil on canvas",
    condition_status: "Good - Conservation stable",
    created_at: "2022-11-20T10:00:00.000Z",
    updated_at: "2024-05-12T11:00:00.000Z",
  },
  {
    contribution_id: 3,
    artifact_id: 3,
    catalog_id: 3,
    title: "Original Jose Rizal Letter to Daet Patriots (1891)",
    donor_name: "Daet Historical Committee",
    contributor_name: "Daet Historical Committee",
    provenance: "Daet, Camarines Norte",
    culture: "Propaganda Movement / Philippine Revolution",
    acquisition_date: "2023-01-10",
    contribution_type: "donation",
    display_status: "On Display",
    current_location: "Revolutionary Archives Showcase",
    on_display: true,
    last_maintenance_at: "2024-04-05",
    contract_expires_at: null,
    donor_description: "Handwritten Spanish correspondence regarding civic reforms, addressed to founding members of the first Rizal Monument in the country.",
    curatorial_description: "Crucial historic paper manuscript kept in an argon gas micro-climate enclosure with UV-filtering glass.",
    images: ["41986-20250919-549469290.webp"],
    image_urls: ["/uploads/pictures/41986-20250919-549469290.webp"],
    related_image_urls: [],
    dimensions: JSON.stringify([{ label: "Page", value: "21.5 x 28 cm" }]),
    material: "Rag paper, iron gall ink",
    condition_status: "Fragile - Climate Controlled",
    created_at: "2023-01-10T12:00:00.000Z",
    updated_at: "2024-04-05T09:00:00.000Z",
  },
  {
    contribution_id: 4,
    artifact_id: 4,
    catalog_id: 4,
    title: "Pre-Hispanic Burial Jar of Capalonga",
    donor_name: "Capalonga Archaeological Society",
    contributor_name: "Capalonga Archaeological Society",
    provenance: "Capalonga, Camarines Norte",
    culture: "Iron Age Bicol (c. 500 BCE - 500 CE)",
    acquisition_date: "2023-08-14",
    contribution_type: "donation",
    display_status: "On Display",
    current_location: "Archaeology Chamber",
    on_display: true,
    last_maintenance_at: "2024-03-20",
    contract_expires_at: null,
    donor_description: "Large earthenware secondary burial vessel with geometric incised neck patterns and anthropomorphic lid crest.",
    curatorial_description: "Discovered intact along the littoral caves of coastal Capalonga. Confirms ancient secondary mortuary rites in Camarines Norte.",
    images: ["42987-20250919-27942155.webp"],
    image_urls: ["/uploads/pictures/42987-20250919-27942155.webp"],
    related_image_urls: [],
    dimensions: JSON.stringify([{ label: "Height", value: "65 cm" }, { label: "Diameter", value: "48 cm" }]),
    material: "Low-fired terracotta earthenware",
    condition_status: "Restored",
    created_at: "2023-08-14T08:30:00.000Z",
    updated_at: "2024-03-20T16:00:00.000Z",
  },
  {
    contribution_id: 5,
    artifact_id: 5,
    catalog_id: 5,
    title: "18th-Century Liturgical Brass Candlestick",
    donor_name: "San Vicente Parish Diocese",
    contributor_name: "San Vicente Parish Diocese",
    provenance: "San Vicente, Camarines Norte",
    culture: "Spanish-Colonial Religious Art",
    acquisition_date: "2023-09-02",
    contribution_type: "lending",
    display_status: "In Storage",
    current_location: "Vault Storage A - Metalwork Rack",
    on_display: false,
    last_maintenance_at: "2024-07-01",
    contract_expires_at: "2026-09-02",
    donor_description: "Cast bronze candlestick crafted by local artisans with floral acanthus leaves, used in Spanish colonial church rituals.",
    curatorial_description: "Shows authentic baroque influence melded with local casting techniques. Currently scheduled for surface stabilization.",
    images: ["43614-20250919-419299415.webp"],
    image_urls: ["/uploads/pictures/43614-20250919-419299415.webp"],
    related_image_urls: [],
    dimensions: JSON.stringify([{ label: "Height", value: "45 cm" }, { label: "Weight", value: "6.2 kg" }]),
    material: "Cast brass and bronze",
    condition_status: "Good",
    created_at: "2023-09-02T14:00:00.000Z",
    updated_at: "2024-07-01T15:00:00.000Z",
  },
  {
    contribution_id: 6,
    artifact_id: 6,
    catalog_id: 6,
    title: "Traditional Bicolano Abaca Woven Tapis",
    donor_name: "Mercedes Weavers Guild",
    contributor_name: "Mercedes Weavers Guild",
    provenance: "Mercedes, Camarines Norte",
    culture: "Indigenous Bicolano Textile",
    acquisition_date: "2024-02-18",
    contribution_type: "donation",
    display_status: "On Display",
    current_location: "Ethnography Wing",
    on_display: true,
    last_maintenance_at: "2024-06-25",
    contract_expires_at: null,
    donor_description: "Naturally dyed abaca ceremonial wrap featuring heritage diamond motifs and native root dyes.",
    curatorial_description: "Preserved using acid-free mounting. Showcases vanishing weaving techniques unique to coastal Bicol communities.",
    images: ["44015-20250919-806102424.webp"],
    image_urls: ["/uploads/pictures/44015-20250919-806102424.webp"],
    related_image_urls: [],
    dimensions: JSON.stringify([{ label: "Width", value: "90 cm" }, { label: "Length", value: "180 cm" }]),
    material: "Woven Abaca fiber, natural plant dyes",
    condition_status: "Mint",
    created_at: "2024-02-18T11:00:00.000Z",
    updated_at: "2024-06-25T13:00:00.000Z",
  },
  {
    contribution_id: 7,
    artifact_id: 7,
    catalog_id: 7,
    title: "Spanish Era Daet Municipal Boundary Marker (1876)",
    donor_name: "Provincial Engineering Office",
    contributor_name: "Provincial Engineering Office",
    provenance: "Daet, Camarines Norte",
    culture: "Late 19th Century Civil Architecture",
    acquisition_date: "2023-10-11",
    contribution_type: "donation",
    display_status: "On Display",
    current_location: "Historical Courtyard & Sculpture Garden",
    on_display: true,
    last_maintenance_at: "2024-02-14",
    contract_expires_at: null,
    donor_description: "Carved volcanic coral-stone marker engraved with the royal Spanish seal and town coordinates.",
    curatorial_description: "Historic boundary stone marking the entry to the provincial capital Daet during the Spanish colonial administration.",
    images: ["44048-20250919-540041342.webp"],
    image_urls: ["/uploads/pictures/44048-20250919-540041342.webp"],
    related_image_urls: [],
    dimensions: JSON.stringify([{ label: "Height", value: "110 cm" }, { label: "Weight", value: "185 kg" }]),
    material: "Carved volcanic adobe stone",
    condition_status: "Weathered - Structurally sound",
    created_at: "2023-10-11T13:30:00.000Z",
    updated_at: "2024-02-14T10:00:00.000Z",
  }
];

export const demoArticles = [
  {
    article_id: 1,
    title: "Paracale: The City of Gold in Ancient Philippine History",
    author: "Elena Santos",
    publication_date: "2024-08-15",
    municipality: "Paracale",
    category: "Archaeology & Heritage",
    summary: "How Camarines Norte's ancient gold mines shaped the culture, trade, and identity of the Bicol Peninsula.",
    content: `
      <h2>The Ancient Miners of Camarines Norte</h2>
      <p>Long before foreign explorers set foot on Philippine soil, the town of <strong>Paracale</strong> was already renowned across Southeast Asia as a thriving hub of gold extraction. The name itself derives from <em>'para cale'</em>, referencing the canals and alluvial waterways carved by indigenous miners.</p>
      <p>Artifacts currently housed in <strong>Museo Bulawan</strong> demonstrate that pre-colonial Bicolanos possessed extraordinary metallurgical skill, creating granulated gold beads, ceremonial death masks, and ornate armlets.</p>
      <h3>Preserving Our Cultural Wealth</h3>
      <p>Through modern cataloging and digital conservation initiatives, Museo Bulawan ensures these irreplaceable treasures remain accessible for future generations of scholars, students, and citizens.</p>
    `,
    images: ["/uploads/pictures/39418-20250919-853771693.webp"],
    status: "PUBLISHED",
    created_at: "2024-08-15T09:00:00.000Z",
  },
  {
    article_id: 2,
    title: "The First Rizal Monument: Daet's Eternal Tribute to the National Hero",
    author: "Louis Ricafrente",
    publication_date: "2024-07-28",
    municipality: "Daet",
    category: "History & Monuments",
    summary: "Unveiled in December 1898, Daet's stone monument predates the famous Rizal monument in Luneta.",
    content: `
      <h2>Pioneers in Honoring Dr. Jose Rizal</h2>
      <p>While millions visit Luneta Park each year, few know that the <strong>very first monument in the world</strong> dedicated to Dr. Jose Rizal was erected in <strong>Daet, Camarines Norte</strong>, in 1898, designed by Lt. Col. Antonio Sanz and Ildefonso Alegre.</p>
      <p>Museo Bulawan preserves original correspondence, sketches, and archival photographs of the historical ceremony that inaugurated the three-tiered stone pylon.</p>
    `,
    images: ["/uploads/pictures/41986-20250919-549469290.webp"],
    status: "PUBLISHED",
    created_at: "2024-07-28T10:00:00.000Z",
  },
  {
    article_id: 3,
    title: "Colors of the Countryside: The Amorsolo Collection at Museo Bulawan",
    author: "Elena Santos",
    publication_date: "2024-06-12",
    municipality: "Daet",
    category: "Visual Arts",
    summary: "A celebration of rural Philippine warmth and light immortalized on canvas by National Artist Fernando Amorsolo.",
    content: `
      <h2>The Master of Tropical Sunlight</h2>
      <p>National Artist Fernando Amorsolo captured the soul of Philippine rural serenity like no other. Museo Bulawan's curated exhibition features rare wartime studies, field sketches, and oil masterpieces highlighting countryside perseverance in the Bicol region.</p>
    `,
    images: ["/assets/06-AfternoonMealOfTheWorker 1.svg"],
    status: "PUBLISHED",
    created_at: "2024-06-12T14:00:00.000Z",
  }
];

const today = new Date();
const todayString = today.toISOString().split("T")[0];

export const demoAppointments = [
  {
    appointment_id: 1,
    full_name: "Ateneo Cultural Heritage Research Team",
    email: "heritage.research@ateneo.edu",
    contact_number: "0917-123-4567",
    purpose_of_visit: "Archival Photography & Gold Artifact Study",
    preferred_date: todayString,
    start_time: "09:30 AM",
    end_time: "11:30 AM",
    total_visitors: 12,
    creation_date: new Date(Date.now() - 3600000 * 4).toISOString(),
    AppointmentStatus: { status: "APPROVED" },
    status: "APPROVED",
    type: "Educational Tour",
    institution: "Ateneo de Naga University"
  },
  {
    appointment_id: 2,
    full_name: "Daet National High School - Grade 11 Class",
    email: "daet.highschool@deped.gov.ph",
    contact_number: "0920-987-6543",
    purpose_of_visit: "History Curriculum Field Trip",
    preferred_date: todayString,
    start_time: "01:30 PM",
    end_time: "03:30 PM",
    total_visitors: 45,
    creation_date: new Date(Date.now() - 3600000 * 2).toISOString(),
    AppointmentStatus: { status: "APPROVED" },
    status: "APPROVED",
    type: "School Delegation",
    institution: "DepEd Camarines Norte"
  },
  {
    appointment_id: 3,
    full_name: "Dr. Patrick Gomez & Associates",
    email: "patrick.gomez@up.edu.ph",
    contact_number: "0922-333-4455",
    purpose_of_visit: "Archaeological Assessment & Carbon Dating Consultation",
    preferred_date: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0],
    start_time: "10:00 AM",
    end_time: "12:00 PM",
    total_visitors: 4,
    creation_date: new Date(Date.now() - 3600000 * 24).toISOString(),
    AppointmentStatus: { status: "PENDING" },
    status: "PENDING",
    type: "Research Access",
    institution: "UP Diliman Archaeological Studies"
  },
  {
    appointment_id: 4,
    full_name: "Vinzons Youth Cultural Circle",
    email: "vinzons.youth@gmail.com",
    contact_number: "0915-444-5566",
    purpose_of_visit: "Wenceslao Vinzons Memorial Exhibition Visit",
    preferred_date: new Date(Date.now() + 86400000 * 3).toISOString().split("T")[0],
    start_time: "02:00 PM",
    end_time: "04:00 PM",
    total_visitors: 20,
    creation_date: new Date(Date.now() - 3600000 * 48).toISOString(),
    AppointmentStatus: { status: "PENDING" },
    status: "PENDING",
    type: "Civic Organization",
    institution: "Vinzons Youth Circle"
  }
];

export const demoVisitorRecords = [
  {
    record_id: 1,
    appointment_id: 1,
    full_name: "Maria Theresa Lopez",
    group_name: "Ateneo Cultural Heritage Team",
    check_in_time: "09:35 AM",
    date: todayString,
    status: "PRESENT",
    origin_city: "Naga City",
  },
  {
    record_id: 2,
    appointment_id: 1,
    full_name: "Prof. Armando Reyes",
    group_name: "Ateneo Cultural Heritage Team",
    check_in_time: "09:36 AM",
    date: todayString,
    status: "PRESENT",
    origin_city: "Naga City",
  },
  {
    record_id: 3,
    appointment_id: 2,
    full_name: "Teacher Grace Ramos",
    group_name: "Daet National High School",
    check_in_time: "01:25 PM",
    date: todayString,
    status: "PRESENT",
    origin_city: "Daet",
  }
];

export const demoSchedules = [
  {
    schedule_id: 1,
    title: "Guided Curatorial Exhibition Tour",
    date: todayString,
    start_time: "09:00 AM",
    end_time: "11:00 AM",
    capacity: 50,
    status: "ACTIVE",
    notes: "Regular morning guided walk through pre-colonial and gold galleries"
  },
  {
    schedule_id: 2,
    title: "Afternoon Educational Session",
    date: todayString,
    start_time: "01:00 PM",
    end_time: "04:00 PM",
    capacity: 60,
    status: "ACTIVE",
    notes: "High school and college heritage study sessions"
  },
  {
    schedule_id: 3,
    title: "Special Conservation Workshop",
    date: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0],
    start_time: "10:00 AM",
    end_time: "12:00 PM",
    capacity: 30,
    status: "ACTIVE",
    notes: "Workshop on paper artifact preservation and textile care"
  }
];

export const demoContributions = [
  {
    contribution_id: 1,
    contributor_id: 101,
    status: "approved",
    transfer_status: "transferred",
    submission_date: "2024-05-10",
    created_at: "2024-05-10T08:00:00.000Z",
    updated_at: "2024-06-01T10:00:00.000Z",
    type: "donation",
    Contributor: {
      contributor_id: 101,
      first_name: "Manuel",
      last_name: "Carpio",
      email: "m.carpio@heritage.ph",
      phone: "0917-111-2222",
      province: "Camarines Norte",
      city: "Paracale",
    },
    ContributionArtifact: {
      title: "Paracale Pre-Colonial Gold Bead Necklace",
      description: "Recovered family heirloom with 12th century gold beads",
    }
  },
  {
    contribution_id: 2,
    contributor_id: 102,
    status: "pending",
    transfer_status: "pending",
    submission_date: "2024-09-01",
    created_at: "2024-09-01T11:30:00.000Z",
    updated_at: "2024-09-01T11:30:00.000Z",
    type: "lending",
    Contributor: {
      contributor_id: 102,
      first_name: "Beatriz",
      last_name: "Alcala",
      email: "b.alcala@gmail.com",
      phone: "0919-444-8888",
      province: "Camarines Norte",
      city: "Daet",
    },
    ContributionArtifact: {
      title: "Spanish Colonial Silver Chalice",
      description: "19th century engraved silver liturgical cup for temporary exhibition",
    }
  },
  {
    contribution_id: 3,
    contributor_id: 103,
    status: "completed",
    transfer_status: "transferred",
    submission_date: "2024-03-15",
    created_at: "2024-03-15T09:00:00.000Z",
    updated_at: "2024-04-02T15:00:00.000Z",
    type: "donation",
    Contributor: {
      contributor_id: 103,
      first_name: "Ramon",
      last_name: "Villafuerte",
      email: "r.villafuerte@gmail.com",
      phone: "0922-777-9999",
      province: "Camarines Norte",
      city: "Vinzons",
    },
    ContributionArtifact: {
      title: "WWII Guerrilla Dispatch Radio",
      description: "Used by the Vinzons Guerrilla Unit during resistance operations",
    }
  }
];

export const demoLogs = [
  {
    id: 1,
    user_name: "Louis Ricafrente",
    role: "Admin",
    action: "CATALOG_ARTIFACT",
    model: "Artifact",
    details: "Cataloged new artifact: 'Paracale Pre-Colonial Gold Bead Necklace' (ACC-2023-001)",
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 2,
    user_name: "Louis Ricafrente",
    role: "Admin",
    action: "APPOINTMENT_APPROVED",
    model: "Appointment",
    details: "Approved tour request for 'Ateneo Cultural Heritage Research Team' (12 visitors)",
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 3,
    user_name: "Elena Santos",
    role: "ContentManager",
    action: "ARTICLE_PUBLISHED",
    model: "Article",
    details: "Published article: 'Paracale: The City of Gold in Ancient Philippine History'",
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: 4,
    user_name: "Louis Ricafrente",
    role: "Admin",
    action: "LOGIN_SUCCESS",
    model: "Auth",
    details: "Admin session authenticated from verified workstation IP",
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 5,
    user_name: "System",
    role: "System",
    action: "MAINTENANCE_LOG",
    model: "ArtifactMaintenance",
    details: "Automated climate and humidity check completed for Vault Storage A",
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
  }
];

export const demoWebsiteTraffic = [
  { date: "Mon", visitors: 340, pageViews: 890, bounceRate: 24 },
  { date: "Tue", visitors: 410, pageViews: 1120, bounceRate: 21 },
  { date: "Wed", visitors: 580, pageViews: 1450, bounceRate: 19 },
  { date: "Thu", visitors: 490, pageViews: 1280, bounceRate: 22 },
  { date: "Fri", visitors: 720, pageViews: 1980, bounceRate: 18 },
  { date: "Sat", visitors: 890, pageViews: 2450, bounceRate: 16 },
  { date: "Sun", visitors: 650, pageViews: 1720, bounceRate: 20 },
];
